services:
  postgresql:
    image: postgres:${POSTGRES_TAG}
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    networks:
      - control-plane
    volumes:
      - pgsql-data:/var/lib/postgresql
      - ./init-db.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD}
      GRAFANA_DB_PASSWORD: ${GRAFANA_DB_PASSWORD}

networks:
  control-plane:
    external: true

volumes:
  pgsql-data:
