services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_TAG}
    container_name: n8n
    hostname: n8n
    restart: unless-stopped
    user: "1000"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=n8n.${APP_DOMAIN}
      - WEBHOOK_URL=http://n8n.${APP_DOMAIN}/
      - N8N_PORT=5678
      - N8N_PROXY_HOPS=1
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

    networks:
      - control-plane
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.${APP_DOMAIN}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls=true
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.middlewares=auth

networks:
  control-plane:
    external: true
