services:
  grafana:
    image: grafana/grafana-oss:${GRAFANA_TAG}
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - control-plane
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgresql:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=${GRAFANA_DB_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${APP_DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.middlewares=auth

networks:
  control-plane:
    external: true

volumes:
  grafana-data:
