services:
  mysql:
    image: mysql:${MYSQL_TAG}
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - control-plane
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

networks:
  control-plane:
    external: true

volumes:
  mysql-data:
