services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_TAG}
    container_name: cloudflared
    hostname: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - control-plane
    labels:
      - traefik.enable=false

networks:
  control-plane:
    external: true
